### ISSUE TITLE
Container LXC

### ISSUE THREAD

**Issue by maximeconnolly** [ClubCedille/docker-php#1]
Pourquoi ceci n'est pas un container LXC tandis que le reste de l'infrastructure est en LXC.

**Comment by mikefaille** [comment]
LXC et docker ne sont pas fait pour le même use case.
https://insights.ubuntu.com/2016/04/13/stephane-graber-lxd-2-0-docker-in-lxd-712/

**Comment by mikefaille** [comment]
Duplicate : https://github.com/ClubCedille/docker-debian/issues/1
